version: 0.1

phases:
  install:
    runtime-version:
      java: openjdk8
    commands:
      - echo: Runtime completed.
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
    build:
      commands:
        - echo Build started on `date`
        - mvn clean prepare-package war:exploded
  post_build:
    commands:
       - echo Build completed on `date`
       - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*